In [ ]:
import numpy as np
import random
a = np.linspace(1,10)
a

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
a=np.empty((2,2))
a

array([[6.52242181e-310, 0.00000000e+000],
       [4.96124130e-090, 3.95298584e+179]])

In [ ]:
a=np.ones((4,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
a=np.full((2,2),7)
a

array([[7, 7],
       [7, 7]])

In [ ]:
a=np.zeros_like([[1,2,3],[4,5,6]])
a

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
a=np.ones_like([[1,2,3],[4,5,6]])
a

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
new_list=[1,2,3,4,5]
a=np.array(new_list)
a


array([1, 2, 3, 4, 5])

In [ ]:
a=np.arange(10,49)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [ ]:
a = np.arange(0,9). reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a=np.random.random((30))
array_mean= a.mean()
array_mean

0.5998990358999675

In [ ]:
a=np.random.rand(10,10)
mini=a.min()
maxi=a.max()
mini,maxi

(0.018621230251997245, 0.9991795851631838)

In [ ]:
a=np.zeros((10))
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
arr=[1,2,0,0,4,0]
rev=np.flip(arr)
rev

array([0, 4, 0, 0, 2, 1])

In [ ]:
a=np.array([[1,1,1,1],[1,0,0,1],[1,1,1,1]])
a

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [ ]:
a=np.array([[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1]])
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])